---
- hosts: all
  tasks:

    - name: install with apt
      apt: name={{ item }}
      with_items:
          - zsh
          - tmux
          - emacs-nox
          - python-pip
          - python-virtualenv
          - python-numpy
          - python-matplotlib
          - ipython
          - yaml-mode
      sudo: yes

    - name: install with pip
      pip: name={{ item }}
      with_items:
          - sphinx
      sudo: yes

    - name: clone oh-my-zsh repo
      git: repo=https://github.com/robbyrussell/oh-my-zsh.git dest=~/.oh-my-zsh

    - name: copy dot files
      copy: src=dot_files/{{ item.src }} dest=~/{{ item.dest }}
      with_items:
          - { src: "dot_zshrc", dest: ".zshrc" }
          - { src: "dot_emacs", dest: ".emacs" }

    - name: set zsh as default default shell
      shell: chsh -s /bin/zsh
      sudo: yes
